/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import javax.swing.JOptionPane;
import Core.Estado;
import Core.Inspecao;
import Core.ValorLogico;
import inspecaocelesc.InspecaoCelesc;
import java.sql.Date;

/**
 *
 * @author marco
 */
public class CadastroInspecao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroInspecao
     */
    public CadastroInspecao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroInspecaoPainel1 = new javax.swing.JPanel();
        cadastroInspecaoLabel1 = new javax.swing.JLabel();
        cadastroInspecaoLabel2 = new javax.swing.JLabel();
        cadastroInspecaoLabel3 = new javax.swing.JLabel();
        cadastroInspecaoLabel4 = new javax.swing.JLabel();
        cadastroInspecaoLabel5 = new javax.swing.JLabel();
        cadastroInspecaoLabel6 = new javax.swing.JLabel();
        cadastroInspecaoComboBox1 = new javax.swing.JComboBox<>();
        cadastroInspecaoComboBox2 = new javax.swing.JComboBox<>();
        cadastroInspecaoComboBox3 = new javax.swing.JComboBox<>();
        cadastroInspecaoCampoTexto1 = new javax.swing.JTextField();
        cadastroInspecaoCampoTexto2 = new javax.swing.JTextField();
        cadastroInspecaoBtn1 = new javax.swing.JButton();
        cadastroInspecaoBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("cadastroInspecao"); // NOI18N
        setResizable(false);

        cadastroInspecaoLabel1.setText("Cadastro Inspeção");

        cadastroInspecaoLabel2.setText("Prumo");

        cadastroInspecaoLabel3.setText("Condição fiação");

        cadastroInspecaoLabel4.setText("Conservação");

        cadastroInspecaoLabel5.setText("Data");

        cadastroInspecaoLabel6.setText("Etiqueta Poste");

        cadastroInspecaoComboBox1.setModel(new javax.swing.DefaultComboBoxModel(ValorLogico.values()));
        cadastroInspecaoComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroInspecaoComboBox1ActionPerformed(evt);
            }
        });

        cadastroInspecaoComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Estado.values()));
        cadastroInspecaoComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroInspecaoComboBox2ActionPerformed(evt);
            }
        });

        cadastroInspecaoComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Estado.values()));

        cadastroInspecaoCampoTexto1.setText("DD/MM/YYYY");
        cadastroInspecaoCampoTexto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroInspecaoCampoTexto1MouseClicked(evt);
            }
        });

        cadastroInspecaoCampoTexto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroInspecaoCampoTexto2ActionPerformed(evt);
            }
        });

        cadastroInspecaoBtn1.setText("Cadastrar");
        cadastroInspecaoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroInspecaoBtn1ActionPerformed(evt);
            }
        });

        cadastroInspecaoBtn2.setText("Cancelar");
        cadastroInspecaoBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroInspecaoBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroInspecaoPainel1Layout = new javax.swing.GroupLayout(cadastroInspecaoPainel1);
        cadastroInspecaoPainel1.setLayout(cadastroInspecaoPainel1Layout);
        cadastroInspecaoPainel1Layout.setHorizontalGroup(
            cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroInspecaoPainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastroInspecaoPainel1Layout.createSequentialGroup()
                        .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastroInspecaoLabel3)
                            .addComponent(cadastroInspecaoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastroInspecaoComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroInspecaoComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroInspecaoPainel1Layout.createSequentialGroup()
                        .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadastroInspecaoBtn1)
                            .addComponent(cadastroInspecaoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroInspecaoPainel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cadastroInspecaoComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroInspecaoPainel1Layout.createSequentialGroup()
                                .addComponent(cadastroInspecaoBtn2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(cadastroInspecaoPainel1Layout.createSequentialGroup()
                        .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastroInspecaoLabel5)
                            .addComponent(cadastroInspecaoLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastroInspecaoCampoTexto2)
                            .addComponent(cadastroInspecaoCampoTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(cadastroInspecaoPainel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(cadastroInspecaoLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastroInspecaoPainel1Layout.setVerticalGroup(
            cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroInspecaoPainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroInspecaoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroInspecaoLabel2)
                    .addComponent(cadastroInspecaoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroInspecaoLabel3)
                    .addComponent(cadastroInspecaoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroInspecaoLabel4)
                    .addComponent(cadastroInspecaoComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroInspecaoLabel5)
                    .addComponent(cadastroInspecaoCampoTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroInspecaoLabel6)
                    .addComponent(cadastroInspecaoCampoTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroInspecaoPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroInspecaoBtn1)
                    .addComponent(cadastroInspecaoBtn2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cadastroInspecaoPainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroInspecaoPainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroInspecaoComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroInspecaoComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroInspecaoComboBox2ActionPerformed

    private void cadastroInspecaoCampoTexto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroInspecaoCampoTexto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroInspecaoCampoTexto2ActionPerformed

    private void cadastroInspecaoCampoTexto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroInspecaoCampoTexto1MouseClicked
        this.cadastroInspecaoCampoTexto1.setText("");
    }//GEN-LAST:event_cadastroInspecaoCampoTexto1MouseClicked

    private void cadastroInspecaoComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroInspecaoComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroInspecaoComboBox1ActionPerformed

    private void cadastroInspecaoBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroInspecaoBtn2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_cadastroInspecaoBtn2ActionPerformed

    private void cadastroInspecaoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroInspecaoBtn1ActionPerformed
        Connection con = null;
        try {
            con = SGBD.Conexao.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        boolean prumo;
        boolean conservacao;
        boolean fiacao;
        Date dataSQL=null;
        String etiqueta;
        
        String valor;
        String data;
        
        
        valor = this.cadastroInspecaoComboBox1.getSelectedItem().toString();
        ValorLogico valorEnum = ValorLogico.valueOf(valor);
        prumo = valorEnum.getValor();
        
        valor = this.cadastroInspecaoComboBox2.getSelectedItem().toString();
        Estado valorEnum2 = Estado.valueOf(valor);
        conservacao = valorEnum2.getValor();
        
        valor = this.cadastroInspecaoComboBox3.getSelectedItem().toString();
        valorEnum2 = Estado.valueOf(valor);
        fiacao = valorEnum2.getValor();
        
        data = this.cadastroInspecaoCampoTexto1.getText();
        try{
            dataSQL = InspecaoCelesc.getData(data);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        } 
        
        etiqueta=this.cadastroInspecaoCampoTexto2.getText();
        
        try{
            Inspecao.InserirInspecao(con, prumo, conservacao, fiacao, dataSQL, etiqueta);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso", "Informação", 1);
        
        this.cadastroInspecaoCampoTexto1.setText("DD/MM/YYYY");
        this.cadastroInspecaoCampoTexto2.setText("");
    }//GEN-LAST:event_cadastroInspecaoBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroInspecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroInspecaoBtn1;
    private javax.swing.JButton cadastroInspecaoBtn2;
    private javax.swing.JTextField cadastroInspecaoCampoTexto1;
    private javax.swing.JTextField cadastroInspecaoCampoTexto2;
    private javax.swing.JComboBox<String> cadastroInspecaoComboBox1;
    private javax.swing.JComboBox<String> cadastroInspecaoComboBox2;
    private javax.swing.JComboBox<String> cadastroInspecaoComboBox3;
    private javax.swing.JLabel cadastroInspecaoLabel1;
    private javax.swing.JLabel cadastroInspecaoLabel2;
    private javax.swing.JLabel cadastroInspecaoLabel3;
    private javax.swing.JLabel cadastroInspecaoLabel4;
    private javax.swing.JLabel cadastroInspecaoLabel5;
    private javax.swing.JLabel cadastroInspecaoLabel6;
    private javax.swing.JPanel cadastroInspecaoPainel1;
    // End of variables declaration//GEN-END:variables
}
