/*
 * To change this license heade            @Override
            public void setSelectedItem(Object anItem) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getSelectedItem() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getSize() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getElementAt(int index) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void addListDataListener(ListDataListener l) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Core.Materiais;
import Core.Poste;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class CadastroPoste extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPoste
     */
    public CadastroPoste() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cadastroPostePainel1 = new javax.swing.JPanel();
        cadastroPosteLabel1 = new javax.swing.JLabel();
        cadastroPosteLabel2 = new javax.swing.JLabel();
        cadastroPosteCampo1 = new javax.swing.JTextField();
        cadastroPosteLabel3 = new javax.swing.JLabel();
        cadastroPosteComboBox1 = new javax.swing.JComboBox<>();
        cadastroPosteLabel4 = new javax.swing.JLabel();
        cadastroPosteLabel5 = new javax.swing.JLabel();
        cadastroPosteCampo2 = new javax.swing.JTextField();
        cadastroPosteCampo3 = new javax.swing.JTextField();
        cadastroPosteBtn1 = new javax.swing.JButton();
        cadastroPosteBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("cadastroPoste"); // NOI18N
        setResizable(false);

        cadastroPosteLabel1.setText("Cadastro Poste");

        cadastroPosteLabel2.setText("Etiqueta");

        cadastroPosteCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPosteCampo1ActionPerformed(evt);
            }
        });

        cadastroPosteLabel3.setText("Material");

        cadastroPosteComboBox1.setModel(new javax.swing.DefaultComboBoxModel(Materiais.values()));
        cadastroPosteComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPosteComboBox1ActionPerformed(evt);
            }
        });

        cadastroPosteLabel4.setText("Latitude");

        cadastroPosteLabel5.setText("Longitude");

        cadastroPosteCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPosteCampo2ActionPerformed(evt);
            }
        });

        cadastroPosteCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPosteCampo3ActionPerformed(evt);
            }
        });

        cadastroPosteBtn1.setText("Cadastrar");
        cadastroPosteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPosteBtn1ActionPerformed(evt);
            }
        });

        cadastroPosteBtn2.setText("Cancelar");
        cadastroPosteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPosteBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroPostePainel1Layout = new javax.swing.GroupLayout(cadastroPostePainel1);
        cadastroPostePainel1.setLayout(cadastroPostePainel1Layout);
        cadastroPostePainel1Layout.setHorizontalGroup(
            cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPostePainel1Layout.createSequentialGroup()
                .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroPostePainel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastroPosteLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(cadastroPosteLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroPosteLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroPosteLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastroPosteLabel1)
                            .addComponent(cadastroPosteCampo1)
                            .addComponent(cadastroPosteComboBox1, 0, 94, Short.MAX_VALUE)
                            .addComponent(cadastroPosteCampo2)
                            .addComponent(cadastroPosteCampo3)))
                    .addGroup(cadastroPostePainel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cadastroPosteBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastroPosteBtn2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        cadastroPostePainel1Layout.setVerticalGroup(
            cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPostePainel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cadastroPosteLabel1)
                .addGap(34, 34, 34)
                .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroPosteLabel2)
                    .addComponent(cadastroPosteCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroPosteLabel3)
                    .addComponent(cadastroPosteComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroPosteLabel4)
                    .addComponent(cadastroPosteCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroPosteLabel5)
                    .addComponent(cadastroPosteCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(cadastroPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroPosteBtn1)
                    .addComponent(cadastroPosteBtn2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastroPostePainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroPostePainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPosteCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPosteCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPosteCampo1ActionPerformed

    private void cadastroPosteCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPosteCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPosteCampo2ActionPerformed

    private void cadastroPosteCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPosteCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPosteCampo3ActionPerformed

    private void cadastroPosteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPosteBtn2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_cadastroPosteBtn2ActionPerformed

    private void cadastroPosteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPosteBtn1ActionPerformed
        Connection con = null;
        try {
            con = SGBD.Conexao.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        String etiqueta = this.cadastroPosteCampo1.getText();
        double latitude = Double.valueOf(this.cadastroPosteCampo2.getText());
        double longitude = Double.valueOf(this.cadastroPosteCampo3.getText());
        String materialObtido = this.cadastroPosteComboBox1.getSelectedItem().toString();
        Materiais material = Materiais.valueOf(materialObtido);
        int valorMaterial = material.getValor();
        
        try{
            Poste.inserirPoste(con, etiqueta, valorMaterial, latitude, longitude);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso", "Informação", 1);
        
        this.cadastroPosteCampo1.setText("");
        this.cadastroPosteCampo2.setText("");
        this.cadastroPosteCampo3.setText("");
    }//GEN-LAST:event_cadastroPosteBtn1ActionPerformed

    private void cadastroPosteComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPosteComboBox1ActionPerformed

    }//GEN-LAST:event_cadastroPosteComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPoste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastroPosteBtn1;
    private javax.swing.JButton cadastroPosteBtn2;
    private javax.swing.JTextField cadastroPosteCampo1;
    private javax.swing.JTextField cadastroPosteCampo2;
    private javax.swing.JTextField cadastroPosteCampo3;
    private javax.swing.JComboBox<String> cadastroPosteComboBox1;
    private javax.swing.JLabel cadastroPosteLabel1;
    private javax.swing.JLabel cadastroPosteLabel2;
    private javax.swing.JLabel cadastroPosteLabel3;
    private javax.swing.JLabel cadastroPosteLabel4;
    private javax.swing.JLabel cadastroPosteLabel5;
    private javax.swing.JPanel cadastroPostePainel1;
    // End of variables declaration//GEN-END:variables
}
