/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Core.Poste;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class ExcluirPoste extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirPoste
     */
    public ExcluirPoste() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExcluirPostePainel1 = new javax.swing.JPanel();
        excluirPosteLabel1 = new javax.swing.JLabel();
        excluirPosteLabel2 = new javax.swing.JLabel();
        excluirPosteCampo1 = new javax.swing.JTextField();
        excluirPosteLabel3 = new javax.swing.JLabel();
        excluirPosteLabel4 = new javax.swing.JLabel();
        excluirPosteCampo2 = new javax.swing.JTextField();
        excluirPosteBtn1 = new javax.swing.JButton();
        excluirPosteBtn2 = new javax.swing.JButton();
        excluirPosteBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("excluirPoste"); // NOI18N
        setResizable(false);

        excluirPosteLabel1.setText("Excluir Poste");

        excluirPosteLabel2.setText("ID");

        excluirPosteCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPosteCampo1ActionPerformed(evt);
            }
        });

        excluirPosteLabel3.setText("OU");

        excluirPosteLabel4.setText("Etiqueta");

        excluirPosteCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPosteCampo2ActionPerformed(evt);
            }
        });

        excluirPosteBtn1.setText("ID");
        excluirPosteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPosteBtn1ActionPerformed(evt);
            }
        });

        excluirPosteBtn2.setText("Etiqueta");
        excluirPosteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPosteBtn2ActionPerformed(evt);
            }
        });

        excluirPosteBtn3.setText("Cancelar");
        excluirPosteBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPosteBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExcluirPostePainel1Layout = new javax.swing.GroupLayout(ExcluirPostePainel1);
        ExcluirPostePainel1.setLayout(ExcluirPostePainel1Layout);
        ExcluirPostePainel1Layout.setHorizontalGroup(
            ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExcluirPostePainel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(excluirPosteLabel3)
                .addGap(48, 48, 48))
            .addGroup(ExcluirPostePainel1Layout.createSequentialGroup()
                .addGroup(ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExcluirPostePainel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirPosteLabel4)
                            .addComponent(excluirPosteLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirPosteCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirPosteCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ExcluirPostePainel1Layout.createSequentialGroup()
                        .addComponent(excluirPosteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirPosteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExcluirPostePainel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(excluirPosteBtn3))
                    .addGroup(ExcluirPostePainel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(excluirPosteLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExcluirPostePainel1Layout.setVerticalGroup(
            ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExcluirPostePainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(excluirPosteLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirPosteLabel2)
                    .addComponent(excluirPosteCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirPosteLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirPosteLabel4)
                    .addComponent(excluirPosteCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExcluirPostePainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirPosteBtn1)
                    .addComponent(excluirPosteBtn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirPosteBtn3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExcluirPostePainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExcluirPostePainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirPosteCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPosteCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirPosteCampo1ActionPerformed

    private void excluirPosteCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPosteCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirPosteCampo2ActionPerformed

    private void excluirPosteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPosteBtn1ActionPerformed
        Connection con = null;
        try {
            con = SGBD.Conexao.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        int id;       
        id = Integer.parseInt(this.excluirPosteCampo1.getText());
        
        try{
            Poste.apagarPoste(con, id);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Excluido com sucesso", "Informação", 1);
    }//GEN-LAST:event_excluirPosteBtn1ActionPerformed

    private void excluirPosteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPosteBtn2ActionPerformed
                Connection con = null;
        try {
            con = SGBD.Conexao.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        String etiqueta;
        
        etiqueta = this.excluirPosteCampo2.getText();
        
                try{
            Poste.apagarPoste(con, etiqueta);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", 0);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Excluido com sucesso", "Informação", 1);
        
    }//GEN-LAST:event_excluirPosteBtn2ActionPerformed

    private void excluirPosteBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPosteBtn3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_excluirPosteBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirPoste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExcluirPostePainel1;
    private javax.swing.JButton excluirPosteBtn1;
    private javax.swing.JButton excluirPosteBtn2;
    private javax.swing.JButton excluirPosteBtn3;
    private javax.swing.JTextField excluirPosteCampo1;
    private javax.swing.JTextField excluirPosteCampo2;
    private javax.swing.JLabel excluirPosteLabel1;
    private javax.swing.JLabel excluirPosteLabel2;
    private javax.swing.JLabel excluirPosteLabel3;
    private javax.swing.JLabel excluirPosteLabel4;
    // End of variables declaration//GEN-END:variables
}
