/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipalPainel1 = new javax.swing.JPanel();
        labelPainel1 = new javax.swing.JLabel();
        menuPrincipalBtn1 = new javax.swing.JButton();
        menuPrincipalBtn3 = new javax.swing.JButton();
        menuPrincipalBtn2 = new javax.swing.JButton();
        menuPrincipalBtn4 = new javax.swing.JButton();
        menuPrincipalBtn5 = new javax.swing.JButton();
        menuPrincipalBtn6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenu1 = new javax.swing.JMenu();
        bntMenu1Op1 = new javax.swing.JMenuItem();
        btnMenu2 = new javax.swing.JMenu();
        btnMenu2Op1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inspeção Celesc");
        setLocation(new java.awt.Point(0, 0));
        setName("menuPrincipal"); // NOI18N
        setResizable(false);

        labelPainel1.setText("Menu Principal");

        menuPrincipalBtn1.setText("Inserir Poste");
        menuPrincipalBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalBtn1ActionPerformed(evt);
            }
        });

        menuPrincipalBtn3.setText("Inserir Inspeção");
        menuPrincipalBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalBtn3ActionPerformed(evt);
            }
        });

        menuPrincipalBtn2.setText("Excluir Poste");
        menuPrincipalBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalBtn2ActionPerformed(evt);
            }
        });

        menuPrincipalBtn4.setText("Excluir Inspeção");
        menuPrincipalBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalBtn4ActionPerformed(evt);
            }
        });

        menuPrincipalBtn5.setText("Exibir Postes");

        menuPrincipalBtn6.setText("Exibir Inspeções");

        javax.swing.GroupLayout menuPrincipalPainel1Layout = new javax.swing.GroupLayout(menuPrincipalPainel1);
        menuPrincipalPainel1.setLayout(menuPrincipalPainel1Layout);
        menuPrincipalPainel1Layout.setHorizontalGroup(
            menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPrincipalBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPrincipalBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPrincipalBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPrincipalPainel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuPrincipalBtn6)
                            .addComponent(menuPrincipalBtn4)))
                    .addGroup(menuPrincipalPainel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(menuPrincipalBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(menuPrincipalPainel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(labelPainel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPrincipalPainel1Layout.setVerticalGroup(
            menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPainel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelPainel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuPrincipalBtn1)
                    .addComponent(menuPrincipalBtn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuPrincipalBtn3)
                    .addComponent(menuPrincipalBtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPrincipalPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuPrincipalBtn5)
                    .addComponent(menuPrincipalBtn6))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        btnMenu1.setText("Inicio");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        bntMenu1Op1.setText("Sair");
        bntMenu1Op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMenu1Op1ActionPerformed(evt);
            }
        });
        btnMenu1.add(bntMenu1Op1);

        jMenuBar1.add(btnMenu1);

        btnMenu2.setText("Ajuda");

        btnMenu2Op1.setText("Sobre");
        btnMenu2Op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2Op1ActionPerformed(evt);
            }
        });
        btnMenu2.add(btnMenu2Op1);

        jMenuBar1.add(btnMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPrincipalPainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipalPainel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPrincipalBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalBtn1ActionPerformed
        new CadastroPoste().setVisible(true);
    }//GEN-LAST:event_menuPrincipalBtn1ActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void bntMenu1Op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMenu1Op1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bntMenu1Op1ActionPerformed

    private void btnMenu2Op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2Op1ActionPerformed
        JOptionPane.showMessageDialog(null, "Trabalho feito por Marco Dionatan Lago", "Sobre", 1);
    }//GEN-LAST:event_btnMenu2Op1ActionPerformed

    private void menuPrincipalBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalBtn3ActionPerformed
        new CadastroInspecao().setVisible(true);
    }//GEN-LAST:event_menuPrincipalBtn3ActionPerformed

    private void menuPrincipalBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalBtn2ActionPerformed
        new ExcluirPoste().setVisible(true);
    }//GEN-LAST:event_menuPrincipalBtn2ActionPerformed

    private void menuPrincipalBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalBtn4ActionPerformed
        new ExcluirInspecao().setVisible(true);
    }//GEN-LAST:event_menuPrincipalBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bntMenu1Op1;
    private javax.swing.JMenu btnMenu1;
    private javax.swing.JMenu btnMenu2;
    private javax.swing.JMenuItem btnMenu2Op1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelPainel1;
    private javax.swing.JButton menuPrincipalBtn1;
    private javax.swing.JButton menuPrincipalBtn2;
    private javax.swing.JButton menuPrincipalBtn3;
    private javax.swing.JButton menuPrincipalBtn4;
    private javax.swing.JButton menuPrincipalBtn5;
    private javax.swing.JButton menuPrincipalBtn6;
    private javax.swing.JPanel menuPrincipalPainel1;
    // End of variables declaration//GEN-END:variables
}
